### ISSUE TITLE
Hello, I had the following problems when Running Infer. Py. I don't know if it was the cause of Tensorpack, which made me very confused. How to solve this problem?

### ISSUE THREAD

**Issue by Diting-li** [SIAAAAAA/CGC-Net#2]
-----Auto Selecting Checkpoint Basing On "valid_dice" Through ">" Comparison
Selecting: ./media/vqdang/logs/v1.0/np_hv/model-29150.index
Having Following Statistics:
	learning_rate: 9.999999747378752e-06
	QueueInput/queue_size: 49.80662536621094
	loss-bce: 0.11510444432497025
	loss-dice: 0.1876249760389328
	loss-mse: 0.019031917676329613
	loss-msge: 0.3226739466190338
	overall-loss: 0.6634671092033386
	DataParallelInferenceRunner/QueueInput/queue_size: 49.90331268310547
	valid_mse: 0.04642050700835553
	valid_acc: 0.9463576229111165
	valid_dice: 0.866723129027714
	epoch_num: 50
	global_step: 29150
[0910 15:18:37 @varmanip.py:215] Checkpoint path ./media/vqdang/logs/v1.0/np_hv/model-29150.index is auto-corrected to ./media/vqdang/logs/v1.0/np_hv/model-29150.
Traceback (most recent call last):
  File "D:/Wonders_Code_files_Pycharm/20200907_cell_split/infer.py", line 183, in <module>
    inferer.run()    
  File "D:/Wonders_Code_files_Pycharm/20200907_cell_split/infer.py", line 149, in run
    pred_config = PredictConfig(model = model_constructor(), session_init = get_model_loader(model_path), input_names  = self.eval_inf_input_tensor_names, output_names = self.eval_inf_output_tensor_names)
  File "C:\Users\Diting\anaconda3\envs\tensorflow1.10\lib\site-packages\tensorpack\predict\config.py", line 79, in __init__
    self.input_signature = model.get_input_signature()
  File "C:\Users\Diting\anaconda3\envs\tensorflow1.10\lib\site-packages\tensorpack\utils\argtools.py", line 192, in wrapper
    value = func(*args, **kwargs)
  File "C:\Users\Diting\anaconda3\envs\tensorflow1.10\lib\site-packages\tensorpack\train\model_desc.py", line 37, in get_input_signature
    inputs = self.inputs()
  File "C:\Users\Diting\anaconda3\envs\tensorflow1.10\lib\site-packages\tensorpack\train\model_desc.py", line 67, in inputs
    raise NotImplementedError()
NotImplementedError

Process finished with exit code 1

**Comment by Abbas009** [comment]
I didn't find any infer.py file in their code. Do you have it?
